-- =====================================================================
-- Distributed Logistics & Dispatch Platform: PostgreSQL schema
-- Three schemas, one owner each. NO foreign keys across schemas.
--   core      -> ASP.NET   (system of record)
--   dispatch  -> go-dispatch (live assignment state)
--   tracking  -> go-ingest / location consumers (location data)
-- Conventions: UUID ids (generated by the service), timestamptz in UTC,
-- version column on mutable aggregates, updated_at set by the application.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid() fallback

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS dispatch;
CREATE SCHEMA IF NOT EXISTS tracking;

-- =====================================================================
-- SCHEMA: core (owned by ASP.NET)
-- =====================================================================

-- ---------- Identity ----------
CREATE TABLE core.users (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email          text        NOT NULL,
    phone          text,
    password_hash  text        NOT NULL,
    full_name      text        NOT NULL,
    status         text        NOT NULL DEFAULT 'Active'
                   CHECK (status IN ('Active','Suspended','Deleted')),
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    deleted_at     timestamptz
);
CREATE UNIQUE INDEX ux_users_email ON core.users (lower(email)) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX ux_users_phone ON core.users (phone) WHERE phone IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE core.roles (
    id    smallint PRIMARY KEY,
    name  text NOT NULL UNIQUE
          CHECK (name IN ('Admin','Dispatcher','Courier','Customer'))
);
INSERT INTO core.roles (id, name) VALUES
    (1,'Admin'), (2,'Dispatcher'), (3,'Courier'), (4,'Customer');

CREATE TABLE core.user_roles (
    user_id  uuid     NOT NULL REFERENCES core.users(id) ON DELETE CASCADE,
    role_id  smallint NOT NULL REFERENCES core.roles(id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE core.refresh_tokens (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      uuid        NOT NULL REFERENCES core.users(id) ON DELETE CASCADE,
    token_hash   text        NOT NULL UNIQUE,       -- store hashes only
    expires_at   timestamptz NOT NULL,
    revoked_at   timestamptz,
    replaced_by  uuid REFERENCES core.refresh_tokens(id),
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_refresh_tokens_user ON core.refresh_tokens (user_id);

-- ---------- Parties ----------
CREATE TABLE core.customers (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          uuid        NOT NULL UNIQUE REFERENCES core.users(id),
    company_name     text,
    default_address  text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz
);

CREATE TABLE core.vehicles (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    plate_no          text        NOT NULL UNIQUE,
    type              text        NOT NULL
                      CHECK (type IN ('Bike','Car','Van','Truck')),
    capacity_weight   numeric(8,2),                  -- kg
    capacity_volume   numeric(8,2),                  -- m3
    status            text        NOT NULL DEFAULT 'Active'
                      CHECK (status IN ('Active','Maintenance','Retired')),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE core.couriers (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid        NOT NULL UNIQUE REFERENCES core.users(id),
    vehicle_id  uuid        REFERENCES core.vehicles(id),
    license_no  text        NOT NULL,
    status      text        NOT NULL DEFAULT 'PendingApproval'
                CHECK (status IN ('PendingApproval','Offline','Available','Busy','Suspended')),
    rating      numeric(3,2) NOT NULL DEFAULT 5.00 CHECK (rating BETWEEN 0 AND 5),
    approved_at timestamptz,
    version     integer     NOT NULL DEFAULT 1,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz
);
-- A vehicle can belong to only one active courier at a time.
CREATE UNIQUE INDEX ux_couriers_vehicle ON core.couriers (vehicle_id)
    WHERE vehicle_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX ix_couriers_status ON core.couriers (status) WHERE deleted_at IS NULL;

-- ---------- Orders ----------
CREATE TABLE core.orders (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_no             text        NOT NULL UNIQUE,
    customer_id          uuid        NOT NULL REFERENCES core.customers(id),
    status               text        NOT NULL DEFAULT 'Created'
                         CHECK (status IN ('Created','Searching','Offered','Assigned',
                                           'PickedUp','Delivered',
                                           'Cancelled','Failed','Unassigned')),
    priority             smallint    NOT NULL DEFAULT 0,
    vehicle_type         text        CHECK (vehicle_type IN ('Bike','Car','Van','Truck')),
    package_description  text,
    package_weight       numeric(8,2),
    requested_pickup_at  timestamptz,
    assigned_courier_id  uuid        REFERENCES core.couriers(id),
    cancelled_reason     text,
    cancelled_by         uuid        REFERENCES core.users(id),
    version              integer     NOT NULL DEFAULT 1,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    completed_at         timestamptz
);
CREATE INDEX ix_orders_customer_created ON core.orders (customer_id, created_at DESC);
CREATE INDEX ix_orders_courier          ON core.orders (assigned_courier_id) WHERE assigned_courier_id IS NOT NULL;
CREATE INDEX ix_orders_active_status    ON core.orders (status, created_at)
    WHERE status IN ('Created','Searching','Offered','Assigned','PickedUp');

CREATE TABLE core.order_stops (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id      uuid        NOT NULL REFERENCES core.orders(id) ON DELETE CASCADE,
    sequence      smallint    NOT NULL,
    type          text        NOT NULL CHECK (type IN ('Pickup','Dropoff')),
    address       text        NOT NULL,
    location      geography(Point, 4326) NOT NULL,
    contact_name  text,
    contact_phone text,
    arrived_at    timestamptz,
    completed_at  timestamptz,
    UNIQUE (order_id, sequence)
);
CREATE INDEX ix_order_stops_location ON core.order_stops USING gist (location);

CREATE TABLE core.order_status_history (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id    uuid        NOT NULL REFERENCES core.orders(id) ON DELETE CASCADE,
    from_status text,
    to_status   text        NOT NULL,
    reason      text,
    actor_type  text        NOT NULL CHECK (actor_type IN ('Customer','Courier','Dispatcher','Admin','System')),
    actor_id    uuid,                                 -- user id, null for System
    occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_order_history_order ON core.order_status_history (order_id, occurred_at);

-- Read model, persisted from assignment.events. Truth during dispatch lives in dispatch schema.
CREATE TABLE core.assignments (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id     uuid        NOT NULL REFERENCES core.orders(id) ON DELETE CASCADE,
    courier_id   uuid        NOT NULL REFERENCES core.couriers(id),
    status       text        NOT NULL
                 CHECK (status IN ('Assigned','PickedUp','Completed','Cancelled','Reassigned')),
    assigned_at  timestamptz NOT NULL,
    completed_at timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);
-- Only one live assignment per order.
CREATE UNIQUE INDEX ux_assignments_active_order ON core.assignments (order_id)
    WHERE status IN ('Assigned','PickedUp');
CREATE INDEX ix_assignments_courier ON core.assignments (courier_id, status);

-- ---------- Idempotency / messaging ----------
CREATE TABLE core.idempotency_keys (
    user_id          uuid        NOT NULL,
    key              text        NOT NULL,
    request_hash     text        NOT NULL,
    response_status  integer,
    response_body    jsonb,
    created_at       timestamptz NOT NULL DEFAULT now(),
    expires_at       timestamptz NOT NULL,
    PRIMARY KEY (user_id, key)
);
CREATE INDEX ix_idempotency_expires ON core.idempotency_keys (expires_at);

CREATE TABLE core.outbox_messages (
    id              uuid PRIMARY KEY,                -- becomes eventId
    aggregate_type  text        NOT NULL,
    aggregate_id    uuid        NOT NULL,
    topic           text        NOT NULL,
    message_key     text        NOT NULL,            -- Kafka partition key
    event_type      text        NOT NULL,
    event_version   integer     NOT NULL DEFAULT 1,
    payload         jsonb       NOT NULL,
    headers         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),
    published_at    timestamptz
);
CREATE INDEX ix_core_outbox_unpublished ON core.outbox_messages (created_at)
    WHERE published_at IS NULL;

CREATE TABLE core.processed_events (
    event_id       uuid        NOT NULL,
    consumer_name  text        NOT NULL,
    processed_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id, consumer_name)
);

-- =====================================================================
-- SCHEMA: dispatch (owned by go-dispatch)
-- Links to core are by ID only (logical, kept consistent by events).
-- =====================================================================

-- Local snapshot built from order.created. Not a copy of the full order.
CREATE TABLE dispatch.dispatch_orders (
    order_id             uuid PRIMARY KEY,           -- = core.orders.id (logical)
    state                text        NOT NULL DEFAULT 'Searching'
                         CHECK (state IN ('Searching','Offered','Assigned',
                                          'Cancelled','Unassigned','Completed')),
    pickup_location      geography(Point, 4326) NOT NULL,
    vehicle_type         text,
    priority             smallint    NOT NULL DEFAULT 0,
    attempt_count        integer     NOT NULL DEFAULT 0,
    search_radius_m      integer     NOT NULL,
    current_offer_id     uuid,
    assigned_courier_id  uuid,                        -- = core.couriers.id (logical)
    version              integer     NOT NULL DEFAULT 1,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_dispatch_orders_state ON dispatch.dispatch_orders (state)
    WHERE state IN ('Searching','Offered');

CREATE TABLE dispatch.offers (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id      uuid        NOT NULL REFERENCES dispatch.dispatch_orders(order_id) ON DELETE CASCADE,
    courier_id    uuid        NOT NULL,               -- logical link to core.couriers
    attempt_no    integer     NOT NULL,
    status        text        NOT NULL DEFAULT 'Pending'
                  CHECK (status IN ('Pending','Accepted','Rejected','Expired','Cancelled')),
    score         numeric(10,4),
    offered_at    timestamptz NOT NULL DEFAULT now(),
    expires_at    timestamptz NOT NULL,
    responded_at  timestamptz,
    UNIQUE (order_id, courier_id, attempt_no)         -- idempotent offer creation
);
-- DB-level guard against double assignment:
CREATE UNIQUE INDEX ux_offers_one_pending_per_order   ON dispatch.offers (order_id)   WHERE status = 'Pending';
CREATE UNIQUE INDEX ux_offers_one_pending_per_courier ON dispatch.offers (courier_id) WHERE status = 'Pending';
-- Used by the timeout sweeper:
CREATE INDEX ix_offers_pending_expiry ON dispatch.offers (expires_at) WHERE status = 'Pending';

ALTER TABLE dispatch.dispatch_orders
    ADD CONSTRAINT fk_dispatch_current_offer
    FOREIGN KEY (current_offer_id) REFERENCES dispatch.offers(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE dispatch.dispatch_transitions (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id    uuid        NOT NULL REFERENCES dispatch.dispatch_orders(order_id) ON DELETE CASCADE,
    from_state  text,
    to_state    text        NOT NULL,
    trigger     text        NOT NULL,                 -- e.g. OrderCreated, OfferRejected, OfferExpired
    occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_dispatch_transitions_order ON dispatch.dispatch_transitions (order_id, occurred_at);

-- Local read model fed by courier.events. Dispatch never queries core.
CREATE TABLE dispatch.courier_profiles (
    courier_id    uuid PRIMARY KEY,                   -- = core.couriers.id (logical)
    status        text        NOT NULL,
    vehicle_type  text,
    rating        numeric(3,2) NOT NULL DEFAULT 5.00,
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_courier_profiles_status ON dispatch.courier_profiles (status);

CREATE TABLE dispatch.dispatch_config (
    key         text PRIMARY KEY,
    value       text        NOT NULL,
    updated_at  timestamptz NOT NULL DEFAULT now()
);
INSERT INTO dispatch.dispatch_config (key, value) VALUES
    ('offer_ttl_seconds',        '15'),
    ('initial_radius_m',         '2000'),
    ('radius_step_m',            '1000'),
    ('max_radius_m',             '8000'),
    ('max_attempts',             '10'),
    ('geo_result_limit',         '10');

CREATE TABLE dispatch.outbox_messages (
    id              uuid PRIMARY KEY,
    aggregate_type  text        NOT NULL,
    aggregate_id    uuid        NOT NULL,
    topic           text        NOT NULL,
    message_key     text        NOT NULL,
    event_type      text        NOT NULL,
    event_version   integer     NOT NULL DEFAULT 1,
    payload         jsonb       NOT NULL,
    headers         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),
    published_at    timestamptz
);
CREATE INDEX ix_dispatch_outbox_unpublished ON dispatch.outbox_messages (created_at)
    WHERE published_at IS NULL;

CREATE TABLE dispatch.processed_events (
    event_id       uuid        NOT NULL,
    consumer_name  text        NOT NULL,
    processed_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id, consumer_name)
);

-- =====================================================================
-- SCHEMA: tracking (owned by go-ingest and location consumers)
-- =====================================================================

-- Partitioned by day. Inserted in batches only. Partition key must be in the PK.
CREATE TABLE tracking.courier_location_history (
    courier_id   uuid        NOT NULL,                -- logical link to core.couriers
    recorded_at  timestamptz NOT NULL,
    location     geography(Point, 4326) NOT NULL,
    speed_kmh    real,
    heading      real,
    accuracy_m   real,
    order_id     uuid,                                -- logical link to core.orders
    PRIMARY KEY (courier_id, recorded_at)
) PARTITION BY RANGE (recorded_at);
CREATE INDEX brin_location_recorded_at ON tracking.courier_location_history USING brin (recorded_at);

-- Helper: create one daily partition (call from a scheduled job, a few days ahead).
CREATE OR REPLACE FUNCTION tracking.create_daily_partition(p_day date)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    part_name text := format('courier_location_history_%s', to_char(p_day, 'YYYYMMDD'));
BEGIN
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS tracking.%I PARTITION OF tracking.courier_location_history
         FOR VALUES FROM (%L) TO (%L)',
        part_name, p_day::timestamptz, (p_day + 1)::timestamptz);
END $$;

CREATE TABLE tracking.courier_last_location (
    courier_id   uuid PRIMARY KEY,
    location     geography(Point, 4326) NOT NULL,
    recorded_at  timestamptz NOT NULL,
    status       text,
    updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_last_location_geo ON tracking.courier_last_location USING gist (location);

CREATE TABLE tracking.processed_events (
    event_id       uuid        NOT NULL,
    consumer_name  text        NOT NULL,
    processed_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id, consumer_name)
);

-- =====================================================================
-- Ownership: one group role per service, rights only on its own schema.
-- Create the actual LOGIN users in your init step using Docker secrets
-- and add them to these group roles.
-- =====================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'svc_core')     THEN CREATE ROLE svc_core     NOLOGIN; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'svc_dispatch') THEN CREATE ROLE svc_dispatch NOLOGIN; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'svc_tracking') THEN CREATE ROLE svc_tracking NOLOGIN; END IF;
END $$;

GRANT USAGE ON SCHEMA core     TO svc_core;     GRANT ALL ON ALL TABLES IN SCHEMA core     TO svc_core;
GRANT USAGE ON SCHEMA dispatch TO svc_dispatch; GRANT ALL ON ALL TABLES IN SCHEMA dispatch TO svc_dispatch;
GRANT USAGE ON SCHEMA tracking TO svc_tracking; GRANT ALL ON ALL TABLES IN SCHEMA tracking TO svc_tracking;
ALTER DEFAULT PRIVILEGES IN SCHEMA core     GRANT ALL ON TABLES TO svc_core;
ALTER DEFAULT PRIVILEGES IN SCHEMA dispatch GRANT ALL ON TABLES TO svc_dispatch;
ALTER DEFAULT PRIVILEGES IN SCHEMA tracking GRANT ALL ON TABLES TO svc_tracking;
GRANT EXECUTE ON FUNCTION tracking.create_daily_partition(date) TO svc_tracking;
